# Generated by Django 2.0 on 2020-12-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcw', '0002_auto_20201226_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
