# Generated by Django 2.0 on 2020-12-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcw', '0003_auto_20201226_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sureWorks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
