# Generated by Django 2.0 on 2020-12-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcw', '0004_auto_20201226_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
