# Generated by Django 2.2.10 on 2021-01-05 14:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rcw', '0005_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='config',
            field=jsonfield.fields.JSONField(default=dict, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='sureWorks',
            field=jsonfield.fields.JSONField(default=dict, max_length=200),
        ),
    ]
