# Generated by Django 2.2.10 on 2021-01-05 14:32

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rcw', '0006_auto_20210105_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={'verbose_name': '个人简历信息', 'verbose_name_plural': '个人简历信息'},
        ),
        migrations.RemoveField(
            model_name='userconfig',
            name='config',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='date0',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='date1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='education',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='expect',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='major',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='mobile',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='myCotent',
            field=jsonfield.fields.JSONField(default=dict, max_length=200),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='sex',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='sureWorks',
            field=jsonfield.fields.JSONField(default=dict, max_length=200),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='workYear',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='userconfig',
            table='jian_li',
        ),
    ]
