# Generated by Django 2.2.10 on 2021-01-14 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rcw', '0008_userconfig_statu'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 14, 14, 55, 47, 91325, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
