# Generated by Django 2.2.10 on 2021-01-17 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rcw', '0009_userconfig_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='fuli',
            field=models.CharField(default=datetime.datetime(2021, 1, 17, 16, 16, 26, 747735, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
