FROM python:3.6

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN chmod +x /app/start.sh
RUN pip install --index-url http://pypi.douban.com/simple/ --trusted-host  pypi.douban.com tornado requests && \
rm -rf ~/.cache/pip
CMD python manage.py runserver 0.0.0.0:8000

docker run --name nginxname -d -p 8888:80 -p 21985:21985 -p 21984:21984 -p 21983:21983 -p 21982:21982 -v /home/project/nginx/html:/usr/share/nginx/html -v /home/project/nginx/logs:/etc/nginx/logs -v /home/project/nginx/conf/nginx.conf:/etc/nginx/nginx.conf -v /home/project/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf nginx:latest

